### ISSUE TITLE
OCR don't work with new interface

### ISSUE THREAD

**Issue by Cain-Ish** [random-facades/WFInfo#2]
After added new interface OCR don't work - it lookimg for relict to be located at old position, when they are now more centered and more narrowed.

**Comment by dapal-003** [comment]
![SSFUL-1](https://user-images.githubusercontent.com/11076306/58830922-bb9fec00-864b-11e9-8d4e-c4ec15eee644.png)
We're working at it hard. See attached picture. The new UI made readability worse for OCR so we'll need to improve upon that. We're hoping for a full release on friday.

**Comment by dapal-003** [comment]
WFinfo has been updated to support the new UI. Please update to the latest version and confirm it works.

**Comment by random-facades** [comment]
Going to close this now that we got it updated. 
If you run into issues, please open a new issue or hit us up on discord
