### ISSUE TITLE
newer versions seem to have broken the "auto" feature

### ISSUE THREAD

**Issue by imsoenthused** [random-facades/WFInfo#9]
Enjoying the new style overlay, and everything works great as long as I set it to manual, but auto, which was working fine for me, now either doesn't pop up at all or pops up after the reward screen has passed.

**Comment by dapal-003** [comment]
Hi there, could you please update to the latest version? I've published a few updates fixing some scaling issues. I've confirmed with other users that auto is working on multiple machines

**Comment by imsoenthused** [comment]
Seems to be fixed, I apologize.
